import pygame

# Инициализация Pygame
pygame.init()

# Установка размера окна
screen_width = 800
screen_height = 600
screen = pygame.display.set_mode((screen_width, screen_height))

# Название окна
pygame.display.set_caption("Вывод нажатых клавиш")

x = {
    'a': pygame.K_a,
    'b': pygame.K_b,
    'c': pygame.K_c,
    'd': pygame.K_d,
    'e': pygame.K_e,
    'f': pygame.K_f,
    'g': pygame.K_g,
    'h': pygame.K_h,
    'i': pygame.K_i,
    'j': pygame.K_j,
    'k': pygame.K_k,
    'l': pygame.K_l,
    'm': pygame.K_m,
    'n': pygame.K_n,
    'o': pygame.K_o,
    'p': pygame.K_p,
    'q': pygame.K_q,
    'r': pygame.K_r,
    's': pygame.K_s,
    't': pygame.K_t,
    'u': pygame.K_u,
    'v': pygame.K_v,
    'w': pygame.K_w,
    'x': pygame.K_x,
    'y': pygame.K_y,
    'z': pygame.K_z,
    '0': pygame.K_0,
    '1': pygame.K_1,
    '2': pygame.K_2,
    '3': pygame.K_3,
    '4': pygame.K_4,
    '5': pygame.K_5,
    '6': pygame.K_6,
    '7': pygame.K_7,
    '8': pygame.K_8,
    '9': pygame.K_9,
    '-': pygame.K_MINUS,
    '=': pygame.K_EQUALS,
    'numlock': pygame.K_NUMLOCK,
    '[0]': pygame.K_KP0,
    '[1]': pygame.K_KP1,
    '[2]': pygame.K_KP2,
    '[3]': pygame.K_KP3,
    '[4]': pygame.K_KP4,
    '[5]': pygame.K_KP5,
    '[6]': pygame.K_KP6,
    '[7]': pygame.K_KP7,
    '[8]': pygame.K_KP8,
    '[9]': pygame.K_KP9,
    '[-]': pygame.K_KP_MINUS,
    '[+]': pygame.K_KP_PLUS,
    '[*]': pygame.K_KP_MULTIPLY,
    '[/]': pygame.K_KP_DIVIDE,
    'enter': pygame.K_KP_ENTER,
    '[.]': pygame.K_KP_PERIOD,
    'escape': pygame.K_ESCAPE,
    'space': pygame.K_SPACE,
    'tab': pygame.K_TAB,
    'return': pygame.K_RETURN,
    'backspace': pygame.K_BACKSPACE,
    'up': pygame.K_UP,
    'down': pygame.K_DOWN,
    'left': pygame.K_LEFT,
    'right': pygame.K_RIGHT,
    'f1': pygame.K_F1,
    'f2': pygame.K_F2,
    'f3': pygame.K_F3,
    'f4': pygame.K_F4,
    'f5': pygame.K_F5,
    'f6': pygame.K_F6,
    'f7': pygame.K_F7,
    'f8': pygame.K_F8,
    'f9': pygame.K_F9,
    'f10': pygame.K_F10,
    'f11': pygame.K_F11,
    'f12': pygame.K_F12,
    'num lock': pygame.K_NUMLOCK,
    'break': pygame.K_BREAK,
    'scroll lock': pygame.K_SCROLLOCK,
    'print screen': pygame.K_PRINTSCREEN,
    'pause': pygame.K_PAUSE,
    'insert': pygame.K_INSERT,
    'home': pygame.K_HOME,
    'page_up': pygame.K_PAGEUP,
    'delete': pygame.K_DELETE,
    'end': pygame.K_END,
    'page down': pygame.K_PAGEDOWN,
    'page up': pygame.K_PAGEUP,
    'left shift': pygame.K_LSHIFT,
    'right shift': pygame.K_RSHIFT,
    'left ctrl': pygame.K_LCTRL,
    'right ctrl': pygame.K_RCTRL,
    'right meta': pygame.K_RMETA,
    'left meta': pygame.K_LMETA,
    'right alt': pygame.K_RALT,
    'left alt': pygame.K_LALT,
    'caps lock': pygame.K_CAPSLOCK,
    '[': pygame.K_LEFTBRACKET,
    ']': pygame.K_RIGHTBRACKET,
    '`': pygame.K_BACKQUOTE,
    ',': pygame.K_COMMA,
    '.': pygame.K_PERIOD,
    '/': pygame.K_SLASH,
    ';': pygame.K_SEMICOLON,
    '\'': pygame.K_QUOTE,
    '\\': pygame.K_BACKSLASH,
        pygame.K_a: 'a',
    pygame.K_b: 'b',
    pygame.K_c: 'c',
    pygame.K_d: 'd',
    pygame.K_e: 'e',
    pygame.K_f: 'f',
    pygame.K_g: 'g',
    pygame.K_h: 'h',
    pygame.K_i: 'i',
    pygame.K_j: 'j',
    pygame.K_k: 'k',
    pygame.K_l: 'l',
    pygame.K_m: 'm',
    pygame.K_n: 'n',
    pygame.K_o: 'o',
    pygame.K_p: 'p',
    pygame.K_q: 'q',
    pygame.K_r: 'r',
    pygame.K_s: 's',
    pygame.K_t: 't',
    pygame.K_u: 'u',
    pygame.K_v: 'v',
    pygame.K_w: 'w',
    pygame.K_x: 'x',
    pygame.K_y: 'y',
    pygame.K_z: 'z',
    pygame.K_0: '0',
    pygame.K_1: '1',
    pygame.K_2: '2',
    pygame.K_3: '3',
    pygame.K_4: '4',
    pygame.K_5: '5',
    pygame.K_6: '6',
    pygame.K_7: '7',
    pygame.K_8: '8',
    pygame.K_9: '9',
    pygame.K_MINUS: '-',
    pygame.K_EQUALS: '=',
    pygame.K_NUMLOCK: 'numlock',
    pygame.K_KP0: '[0]',
    pygame.K_KP1: '[1]',
    pygame.K_KP2: '[2]',
    pygame.K_KP3: '[3]',
    pygame.K_KP4: '[4]',
    pygame.K_KP5: '[5]',
    pygame.K_KP6: '[6]',
    pygame.K_KP7: '[7]',
    pygame.K_KP8: '[8]',
    pygame.K_KP9: '[9]',
    pygame.K_KP_MINUS: '[-]',
    pygame.K_KP_PLUS: '[+]',
    pygame.K_KP_MULTIPLY: '[*]',
    pygame.K_KP_DIVIDE: '[/]',
    pygame.K_KP_ENTER: 'enter',
    pygame.K_KP_PERIOD: '[.]',
    pygame.K_ESCAPE: 'escape',
    pygame.K_SPACE: 'space',
    pygame.K_TAB: 'tab',
    pygame.K_RETURN: 'return',
    pygame.K_BACKSPACE: 'backspace',
    pygame.K_UP: 'up',
    pygame.K_DOWN: 'down',
    pygame.K_LEFT: 'left',
    pygame.K_RIGHT: 'right',
    pygame.K_F1: 'f1',
    pygame.K_F2: 'f2',
    pygame.K_F3: 'f3',
    pygame.K_F4: 'f4',
    pygame.K_F5: 'f5',
    pygame.K_F6: 'f6',
    pygame.K_F7: 'f7',
    pygame.K_F8: 'f8',
    pygame.K_F9: 'f9',
    pygame.K_F10: 'f10',
    pygame.K_F11: 'f11',
    pygame.K_F12: 'f12',
    pygame.K_NUMLOCK: 'num lock',
    pygame.K_BREAK: 'break',
    pygame.K_SCROLLOCK: 'scroll lock',
    pygame.K_PRINTSCREEN: 'print screen',
    pygame.K_PAUSE: 'pause',
    pygame.K_INSERT: 'insert',
    pygame.K_HOME: 'home',
    pygame.K_PAGEUP: 'page_up',
    pygame.K_DELETE: 'delete',
    pygame.K_END: 'end',
    pygame.K_PAGEDOWN: 'page down',
    pygame.K_PAGEUP: 'page up',
    pygame.K_LSHIFT: 'left shift',
    pygame.K_RSHIFT: 'right shift',
    pygame.K_LCTRL: 'left ctrl',
    pygame.K_RCTRL: 'right ctrl',
    pygame.K_RMETA: 'right meta',
    pygame.K_LMETA: 'left meta',
    pygame.K_RALT: 'right alt',
    pygame.K_LALT: 'left alt',
    pygame.K_CAPSLOCK: 'caps lock',
    pygame.K_LEFTBRACKET: '[',
    pygame.K_RIGHTBRACKET: ']',
    pygame.K_BACKQUOTE: '`',
    pygame.K_COMMA: ',',
    pygame.K_PERIOD: '.',
    pygame.K_SLASH: '/',
    pygame.K_SEMICOLON: ';',
    pygame.K_QUOTE: '\'',
    pygame.K_BACKSLASH: '\\'
}

# Основной цикл игры
running = True
while running:
    # Обработка событий
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
        elif event.type == pygame.KEYDOWN:
            my_key = pygame.key.name(event.key)
            print(f'{my_key=}')
            print(f'{x[my_key]}')
            print('-' * 89)
            
    # Обновление экрана
    pygame.display.flip()

# Выход из Pygame
pygame.quit()
